import React, { useState } from 'react';
import { X, Plus, Trash2, Edit, Save, Play, AlertCircle, CheckCircle, Code } from 'lucide-react';
import { usePluginStore } from '../store/usePluginStore';
import { Plugin } from '../types/plugin';
import { PluginExecutor } from '../services/pluginService';
import { useTranslation } from 'react-i18next';
import clsx from 'clsx';
import { toast } from 'react-toastify';

interface PluginManagerModalProps {
    onClose: () => void;
}

const DEFAULT_SCRIPT_TEMPLATE = `// Return an object with a search function
return {
  search: async (query) => {
    // Example: Fetch from an API
    // const res = await context.fetch('https://api.example.com/search?q=' + encodeURIComponent(query));
    // const data = await res.json();
    
    // Return array of results
    return [
      {
        title: "Example: " + query,
        year: "2024",
        description: "Generated by plugin",
        type: "Movie"
      }
    ];
  }
};`;

export const PluginManagerModal: React.FC<PluginManagerModalProps> = ({ onClose }) => {
    const { t } = useTranslation();
    const { plugins, addPlugin, updatePlugin, removePlugin, togglePlugin } = usePluginStore();
    const [editingId, setEditingId] = useState<string | null>(null);
    const [formData, setFormData] = useState({
        name: '',
        version: '1.0.0',
        author: '',
        description: '',
        script: DEFAULT_SCRIPT_TEMPLATE
    });
    const [testQuery, setTestQuery] = useState('Avatar');
    const [testResult, setTestResult] = useState<any>(null);
    const [isTesting, setIsTesting] = useState(false);

    const resetForm = () => {
        setFormData({
            name: '',
            version: '1.0.0',
            author: '',
            description: '',
            script: DEFAULT_SCRIPT_TEMPLATE
        });
        setEditingId(null);
        setTestResult(null);
    };

    const handleEdit = (plugin: Plugin) => {
        setEditingId(plugin.id);
        setFormData({
            name: plugin.name,
            version: plugin.version,
            author: plugin.author,
            description: plugin.description,
            script: plugin.script
        });
        setTestResult(null);
    };

    const handleSave = () => {
        if (!formData.name || !formData.script) {
            toast.error("Name and script are required");
            return;
        }

        if (editingId) {
            updatePlugin(editingId, formData);
            toast.success("Plugin updated");
        } else {
            addPlugin(formData);
            toast.success("Plugin added");
        }
        resetForm();
    };

    const handleTest = async () => {
        setIsTesting(true);
        setTestResult(null);
        try {
            const tempPlugin = {
                id: 'test',
                ...formData,
                enabled: true,
                createdAt: 0,
                updatedAt: 0
            };
            const executor = new PluginExecutor(tempPlugin);
            const results = await executor.executeSearch(testQuery);
            setTestResult({ success: true, results });
        } catch (e: any) {
            setTestResult({ success: false, error: e.message });
        } finally {
            setIsTesting(false);
        }
    };

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
            <div className="w-full max-w-4xl bg-theme-surface rounded-2xl shadow-2xl border border-theme-border flex flex-col max-h-[90vh]">
                <div className="flex items-center justify-between p-6 border-b border-theme-border">
                    <h2 className="text-xl font-bold text-theme-text flex items-center gap-2">
                        <Code className="w-6 h-6 text-theme-accent" />
                        {t('plugin_manager.title')}
                    </h2>
                    <button onClick={onClose} className="p-1 hover:bg-theme-bg rounded-lg text-theme-subtext transition-colors">
                        <X className="w-5 h-5" />
                    </button>
                </div>

                <div className="flex-1 overflow-hidden flex flex-col md:flex-row">
                    {/* Sidebar: List */}
                    <div className="w-full md:w-1/3 border-r border-theme-border flex flex-col bg-theme-bg/30">
                        <div className="p-4 border-b border-theme-border">
                            <button 
                                onClick={resetForm}
                                className="w-full py-2 bg-theme-accent text-theme-bg rounded-lg font-medium hover:bg-theme-accent-hover transition-colors flex items-center justify-center gap-2"
                            >
                                <Plus className="w-4 h-4" />
                                {t('plugin_manager.new_plugin')}
                            </button>
                        </div>
                        <div className="flex-1 overflow-y-auto p-2 space-y-2 custom-scrollbar">
                            {plugins.map(p => (
                                <div 
                                    key={p.id} 
                                    className={clsx(
                                        "p-3 rounded-lg border cursor-pointer transition-all hover:bg-theme-bg",
                                        editingId === p.id ? "border-theme-accent bg-theme-accent/5" : "border-theme-border bg-theme-surface"
                                    )}
                                    onClick={() => handleEdit(p)}
                                >
                                    <div className="flex justify-between items-start">
                                        <h3 className="font-bold text-sm text-theme-text">{p.name}</h3>
                                        <div className="flex items-center gap-1">
                                            <input 
                                                type="checkbox" 
                                                checked={p.enabled} 
                                                onClick={(e) => e.stopPropagation()}
                                                onChange={() => togglePlugin(p.id)}
                                                className="mr-2"
                                            />
                                        </div>
                                    </div>
                                    <p className="text-xs text-theme-subtext mt-1 line-clamp-2">{p.description || t('plugin_manager.no_description')}</p>
                                    <div className="flex justify-between items-center mt-2">
                                        <span className="text-[10px] bg-theme-bg px-1.5 py-0.5 rounded text-theme-subtext">v{p.version}</span>
                                        <button 
                                            onClick={(e) => { e.stopPropagation(); removePlugin(p.id); }}
                                            className="text-theme-subtext hover:text-red-500 p-1"
                                        >
                                            <Trash2 className="w-3 h-3" />
                                        </button>
                                    </div>
                                </div>
                            ))}
                            {plugins.length === 0 && (
                                <div className="text-center py-8 text-theme-subtext text-sm">
                                    {t('plugin_manager.no_plugins')}
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Main: Editor */}
                    <div className="flex-1 flex flex-col overflow-hidden h-full">
                        <div className="p-6 overflow-y-auto custom-scrollbar space-y-4">
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-xs font-medium text-theme-subtext mb-1">{t('plugin_manager.name_label')}</label>
                                    <input 
                                        value={formData.name}
                                        onChange={e => setFormData({...formData, name: e.target.value})}
                                        className="w-full px-3 py-2 rounded-lg border bg-theme-bg border-theme-border text-theme-text text-sm focus:ring-1 focus:ring-theme-accent outline-none"
                                        placeholder={t('plugin_manager.name_placeholder')}
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-medium text-theme-subtext mb-1">{t('plugin_manager.version_label')}</label>
                                    <input 
                                        value={formData.version}
                                        onChange={e => setFormData({...formData, version: e.target.value})}
                                        className="w-full px-3 py-2 rounded-lg border bg-theme-bg border-theme-border text-theme-text text-sm focus:ring-1 focus:ring-theme-accent outline-none"
                                        placeholder="1.0.0"
                                    />
                                </div>
                            </div>
                            <div>
                                <label className="block text-xs font-medium text-theme-subtext mb-1">{t('plugin_manager.description_label')}</label>
                                <input 
                                    value={formData.description}
                                    onChange={e => setFormData({...formData, description: e.target.value})}
                                    className="w-full px-3 py-2 rounded-lg border bg-theme-bg border-theme-border text-theme-text text-sm focus:ring-1 focus:ring-theme-accent outline-none"
                                    placeholder={t('plugin_manager.description_placeholder')}
                                />
                            </div>

                            <div className="flex-1 flex flex-col min-h-[300px]">
                                <label className="block text-xs font-medium text-theme-subtext mb-1 flex justify-between">
                                    <span>{t('plugin_manager.script_label')}</span>
                                    <span className="text-theme-accent text-[10px]">{t('plugin_manager.script_hint')}</span>
                                </label>
                                <textarea 
                                    value={formData.script}
                                    onChange={e => setFormData({...formData, script: e.target.value})}
                                    className="flex-1 w-full px-3 py-2 rounded-lg border bg-neutral-900 border-theme-border text-green-400 font-mono text-xs focus:ring-1 focus:ring-theme-accent outline-none leading-relaxed resize-none"
                                    spellCheck={false}
                                />
                            </div>

                            {/* Testing Area */}
                            <div className="bg-theme-bg/50 rounded-lg border border-theme-border p-3">
                                <div className="flex gap-2 mb-2">
                                    <input 
                                        value={testQuery}
                                        onChange={e => setTestQuery(e.target.value)}
                                        className="flex-1 px-3 py-1.5 rounded border bg-theme-surface border-theme-border text-theme-text text-sm"
                                        placeholder={t('plugin_manager.test_query_placeholder')}
                                    />
                                    <button 
                                        onClick={handleTest}
                                        disabled={isTesting}
                                        className="px-3 py-1.5 bg-theme-surface border border-theme-accent text-theme-accent rounded text-xs font-medium hover:bg-theme-accent hover:text-white transition-colors flex items-center gap-1"
                                    >
                                        <Play className="w-3 h-3" />
                                        {t('plugin_manager.run_test')}
                                    </button>
                                </div>
                                {testResult && (
                                    <div className={clsx("text-xs font-mono p-2 rounded max-h-32 overflow-y-auto", testResult.success ? "bg-green-900/20 text-green-400" : "bg-red-900/20 text-red-400")}>
                                        <pre>{JSON.stringify(testResult.results || testResult.error, null, 2)}</pre>
                                    </div>
                                )}
                            </div>
                        </div>

                        <div className="p-4 border-t border-theme-border flex justify-end">
                            <button 
                                onClick={handleSave}
                                className="px-6 py-2 bg-theme-accent text-theme-bg rounded-lg font-medium hover:bg-theme-accent-hover transition-colors flex items-center gap-2"
                            >
                                <Save className="w-4 h-4" />
                                {t('plugin_manager.save_plugin')}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};
